ktor:
    application:
        modules:
            - com.malaguita.ApplicationKt.module
    deployment:
        port: 3000
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
